name: YouTube Hebrew Transcription Bot

on:
  schedule:
    - cron: '0 9 * * *'  # Run daily at 9:00 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  transcribe:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install Python dependencies
      run: |
        pip install yt-dlp openai-whisper google-api-python-client google-auth requests
    
    - name: Run transcription bot
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        GOOGLE_DOC_ID: ${{ secrets.GOOGLE_DOC_ID }}
        GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python transcription_bot.py
