name: YouTube Hebrew Transcription Bot

on:
  schedule:
    - cron: '0 9 * * *'    # Run daily at 9:00 AM UTC
  workflow_dispatch:      # Allow manual triggering
    inputs:
      mode:
        description: 'Run mode'
        required: false
        default: 'normal'
        type: choice
        options:
        - normal
        - retry
        - reset
      days_back:
        description: 'Days back to retry (for retry mode)'
        required: false
        default: '7'
        type: string

jobs:
  transcribe:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install Python dependencies
      run: |
        pip install yt-dlp openai-whisper google-api-python-client google-auth requests browser_cookie3
    
    - name: Setup cookies if provided
      run: |
        if [ ! -z "${{ secrets.YOUTUBE_COOKIES_B64 }}" ]; then
          echo "${{ secrets.YOUTUBE_COOKIES_B64 }}" | base64 -d > cookies.txt
        fi
    
    - name: Run transcription bot
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        GOOGLE_DOC_ID: ${{ secrets.GOOGLE_DOC_ID }}
        GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        YOUTUBE_COOKIES_BROWSER: ${{ secrets.YOUTUBE_COOKIES_BROWSER }}
        YOUTUBE_COOKIES_B64: ${{ secrets.YOUTUBE_COOKIES_B64 }}
      run: |
        MODE="${{ github.event.inputs.mode || 'normal' }}"
        DAYS="${{ github.event.inputs.days_back || '7' }}"
        
        if [ "$MODE" = "retry" ]; then
          python transcription_bot.py retry $DAYS
        elif [ "$MODE" = "reset" ]; then
          python transcription_bot.py reset
        else
          python transcription_bot.py
        fi
